### PR TITLE
Refactor support cordova-plugin-file

### PR DESCRIPTION
**Pull request by Donaldcwl**

### CODE REVIEW

**Comment by arivera-skycred** [comment]
@Donaldcwl Correct. When using `cordova-plugin-file` it replaces the type `window.File`, and that is expected. However, it is a problem when using your plugin because your plugin needs the original implementation. This line `window.cordova.require('cordova/modulemapper').getOriginalSymbol(window, 'File')` retrieves the original type. 

I looked at your latest commits and the way you wrote it this time should work fine. Basically, if cordova is not in use, the `CustomFileReader` var will just take the original type from `window`. 

I'll test out your version later tonight, but I don't see any issues after reading through it.

**Comment by Donaldcwl** [comment]
@arivera-skycred Thanks for the clarification. Please info me the result after testing it.

**Comment by arivera-skycred** [comment]
@Donaldcwl can you check in updated compiled files? looks like the distribution files are still the old versions.

**Comment by Donaldcwl** [comment]
@arivera-skycred I didn't commit the build files to GitHub. You may try to build on your machine which should give the same result as I do.

**Comment by arivera-skycred** [comment]
@Donaldcwl sounds good. Testing now. Sorry about that, just easier to pull in the branch via npm.

**Comment by arivera-skycred** [comment]
@Donaldcwl your branch is working as expected. Cheers!

**Pull request merged**
