### PR TITLE
Feature - Support cordova-plugin-file

### PR DESCRIPTION
**Pull request by arivera-skycred**
- Added cordova's modulemapper to get the original type of both `File` and `FileReader`
- Check if cordova is available `window.cordova && window.cordova.require(.....)`
- Backwards compatible with browser

**Note: the test suite is failing on multiple tests due to an out of date dependency `file-api` (https://www.npmjs.com/package/file-api)**

The `file-api` package is using a deprecated method of one of its own dependencies `mime`. `mime.lookup` was replaced with `mime.getType`.

### CODE REVIEW

**Comment by Donaldcwl** [comment]
@arivera-skycred Thanks for the PR
Since the tests did not pass, I have made some modification. However, I don't have a cordova environment. Could you help me to test it?

I have created a new branch with my modification:
https://github.com/Donaldcwl/browser-image-compression/tree/refactor_support_cordova-plugin-file

I want to make sure it is still working with my changes.
Thanks!

**Comment by arivera-skycred** [comment]
@Donaldcwl Added a comment to your branch. Your new approach won't work (unfortunately).

**Comment by arivera-skycred** [comment]
@Donaldcwl also, just an FYI, the approach I used is backwards compatible with standard (non-cordova) browser usage because the `moduleMapper` because that var doesnt get assigned unless cordova is available.

**Comment by Donaldcwl** [comment]
@arivera-skycred 
Since jsdom do not perfectly replicate the browser environment related to File, I stub the `File` and `FileReader` using `file-api`(https://www.npmjs.com/package/file-api) in my test suite.

**Note** that I used an old version of file-api (specified in yarn.lock if you are using yarn) since the new version has some breaking changes that may not work in my case.

It is easier for testing if I use window.File and window.FileReader in the library so it can be mocked in the test.
That's why I made those changes.

**Comment by Donaldcwl** [comment]
@arivera-skycred I have created a new pull request #13, let's discuss there ;)

**Pull request merged**
